### PR TITLE
created the index and css file

### PR DESCRIPTION
**Pull request by Emilsone**
Created the landing page of the URL shortener

### CODE REVIEW

**Comment by micaiah-effiong** [comment]
- Your feature branch should always start with **feat/** example **feat/landing-page**.

- Complete your feature before creating a pull request (make sure your feature is fully create and working before you make a PR)

PEACE ✌️

**Review by Emilsone — COMMENTED** [review]
I added the font family and icons to make the website look good

**Review by Emilsone — COMMENTED** [review]
Added media queries to the design to make it responsive

**Review by micaiah-effiong — APPROVED** [review]
**Great work!**
After this, optimize the code for performance
Use **CDN** where necessary

**Comment by micaiah-effiong** [comment]
> Added media queries to the design to make it responsive

Nice work thank you for your contribution

**Pull request merged**
